// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/bloc/tv_serie_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/tv_serie.dart' as _i9;
import 'package:ditonton/domain/entities/tv_serie_detail.dart' as _i7;
import 'package:ditonton/domain/entities/watchlist.dart' as _i12;
import 'package:ditonton/domain/repositories/watchlist_repository.dart' as _i3;
import 'package:ditonton/domain/usecases/get_tv_serie_detail.dart' as _i4;
import 'package:ditonton/domain/usecases/get_tv_serie_recommendations.dart'
    as _i8;
import 'package:ditonton/domain/usecases/get_watchlist_status.dart' as _i10;
import 'package:ditonton/domain/usecases/remove_watchlist.dart' as _i13;
import 'package:ditonton/domain/usecases/save_watchlist.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistRepository_1 extends _i1.SmartFake
    implements _i3.WatchlistRepository {
  _FakeWatchlistRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTvSerieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSerieDetail extends _i1.Mock implements _i4.GetTvSerieDetail {
  MockGetTvSerieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.TvSerieDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.TvSerieDetail>>.value(
                _FakeEither_0<_i6.Failure, _i7.TvSerieDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.TvSerieDetail>>);
}

/// A class which mocks [GetTvSerieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSerieRecommendations extends _i1.Mock
    implements _i8.GetTvSerieRecommendations {
  MockGetTvSerieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i9.TvSerie>>> execute(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i9.TvSerie>>>.value(
                _FakeEither_0<_i6.Failure, List<_i9.TvSerie>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i9.TvSerie>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i10.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WatchlistRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWatchlistRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.WatchlistRepository);

  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i11.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WatchlistRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWatchlistRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.WatchlistRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(
          _i12.Watchlist? watchlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [watchlist],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [watchlist],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i13.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WatchlistRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWatchlistRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.WatchlistRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(_i12.Watchlist? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [data],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
            _FakeEither_0<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [data],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, String>>);
}
